Edit/bee 83 tech stack links
chingu-voyages/v50-tier3-team-28 pull request #147
Opened 2024-10-07 04:35 UTC by eatwanderexplore

Added links to tech stack. 

I was able to get the images into two columns within the tech stack container, but I'm not sure how to make the tailwindcss image span the width of the container now. Any ideas/know how?

2024-10-07 11:41 UTC, NishaVijai approved these changes
Awesome improvement & will be very useful for the future updates:-) Thank you @eatwanderexplore

2024-10-07 17:18 UTC, ss-deep approved these changes

2024-10-08 04:42 UTC, r1g023 commented
> Added links to tech stack.
> 
> I was able to get the images into two columns within the tech stack container, but I'm not sure how to make the tailwindcss image span the width of the container now. Any ideas/know how?

Hi Jenny if you wanna create a layout where the tailwind logo spans across both columns meanwhile being part of a single row below the tech stack logos above it you can either use a conditional on the tech.name === 'tailwind' (className) and set it's 100% so it spans the whole width but if you want to do it the way you did it with 2 columns and tailwind logo underneath spanning both columsn (to preserve grid) combined you can try: 

className={`flex justify-center items-center px-4 ${
        tech.name === "tailwindcss" ? "col-span-2" : ""
      }`}
      
    And on your image you can try: 
    
    <img
          src={tech.image}
          alt={tech.name}
          className={`w-24 xl:w-32 h-24 xl:h-32 object-contain ${
            tech.name === "tailwindcss" ? "w-full" : "mr-2 xl:mr-4"
          }`}
          
The first one above you can just basically say if the tailwindcss logo is present then make sure it spans both columns and adjust the justify property to be centered since you wanna center the tailwindCSS logo meanwhile preserving the columns that are already centered above the tailwind CSS logo. 

Then the bottom one for your image after your code starts on object-contain you can specify if you have the tailwind image then add a full width so it spans both columns. I tested the above out and it seems to have worked, up to you if you want to implement the changes but I'll still approve since it looks super awesome the way you refactored the techstack logos into its own component.

2024-10-08 04:44 UTC, r1g023 approved these changes

2024-10-08 11:56 UTC, KseniiaRiabova requested changes
I would suggest applying the recommendations provided by @r1g023 before proceeding with the merge.

2024-10-08 16:20 UTC, Valeriusdev approved these changes

2024-10-10 14:48 UTC, KseniiaRiabova approved these changes

2024-10-10 14:48 UTC, merged