Andy graph
chingu-voyages/v50-tier3-team-28 pull request #29
Opened 2024-07-09 22:20 UTC by PongRVA

I created a graph using chart.js to depict declining bee populations.  LMK if you would like anything different.

2024-07-09 22:57 UTC, KseniiaRiabova requested changes
PR should be into development branch from andy-graph branch

2024-07-10 00:08 UTC, Valeriusdev approved these changes

2024-07-10 07:44 UTC, KseniiaRiabova approved these changes

2024-07-10 07:44 UTC, KseniiaRiabova commented
Good Job @PongRVA

2024-07-10 07:45 UTC, merged