Feat/user profile
chingu-voyages/v50-tier3-team-28 pull request #77
Opened 2024-08-06 16:56 UTC by NishaVijai

2024-08-06 21:15 UTC, r1g023 approved these changes

2024-08-06 21:22 UTC, KseniiaRiabova approved these changes
Thank you! Great Job

2024-08-06 23:09 UTC, Valeriusdev requested changes
@NishaVijai, when you have some free time, could you please resolve a merge conflict?

2024-08-07 09:18 UTC, NishaVijai commented
@Valeriusdev I have just resolved merge conflict :-)

2024-08-07 09:27 UTC, Valeriusdev approved these changes

2024-08-07 09:27 UTC, merged